import React, { useState, useEffect } from 'react';
import { TripResult } from '../../types';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';
import { Spinner } from '../ui/Spinner';
import { TabBar } from '../ui/TabBar';
import { ItineraryTab } from './ItineraryTab';
import { WeatherTab } from './WeatherTab';
import { CurrencyTab } from './CurrencyTab';
import { DestinationTab } from './DestinationTab';
import { AgentTraceTab } from './AgentTraceTab';
import { Download, RotateCcw } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface ResultPanelProps {
  result: TripResult | null;
  isLoading: boolean;
  onReset: () => void;
}

const tabs = [
  { id: 'itinerary', label: '📋 Itinerary' },
  { id: 'weather', label: '🌤 Weather' },
  { id: 'currency', label: '💱 Currency' },
  { id: 'destination', label: '🌍 Destination' },
  { id: 'trace', label: '🔍 Agent Trace' },
];

const loadingMessages = [
  'Fetching destination info...',
  'Checking live weather...',
  'Converting currency...',
  'Building your itinerary...',
];

export const ResultPanel: React.FC<ResultPanelProps> = ({ result, isLoading, onReset }) => {
  const [activeTab, setActiveTab] = useState('itinerary');
  const [loadingMessageIndex, setLoadingMessageIndex] = useState(0);

  useEffect(() => {
    if (!isLoading) return;

    const interval = setInterval(() => {
      setLoadingMessageIndex(prev => (prev + 1) % loadingMessages.length);
    }, 2000);

    return () => clearInterval(interval);
  }, [isLoading]);

  const downloadPlan = () => {
    if (!result) return;

    const content = `${result.finalAnswer}\n\n---\nGenerated by Musafir AI`;
    const element = document.createElement('a');
    element.setAttribute(
      'href',
      `data:text/plain;charset=utf-8,${encodeURIComponent(content)}`
    );
    element.setAttribute(
      'download',
      `musafir-trip-${result.destination.toLowerCase().replace(/\s+/g, '-')}.txt`
    );
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  if (!result && !isLoading) {
    return (
      <motion.div
        initial={{ opacity: 0, x: 20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.6 }}
        className="flex items-center justify-center min-h-[600px]"
      >
        <div className="text-center">
          <div className="text-6xl mb-6 animate-float">🗺</div>
          <h3 className="text-2xl font-bold text-zinc-50 mb-2">
            Your trip plan will appear here
          </h3>
          <p className="text-zinc-400 mb-8">
            Fill in the form and hit Plan My Trip
          </p>

          {/* Preview cards */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 max-w-2xl mx-auto">
            {[
              { emoji: '🌤', title: 'Weather Forecast' },
              { emoji: '💱', title: 'Currency Rates' },
              { emoji: '📋', title: 'Itinerary' },
            ].map((item, idx) => (
              <div
                key={idx}
                className="bg-zinc-800/50 rounded-xl p-4 animate-pulse"
              >
                <div className="text-3xl mb-2">{item.emoji}</div>
                <div className="text-sm text-zinc-400">{item.title}</div>
              </div>
            ))}
          </div>
        </div>
      </motion.div>
    );
  }

  if (isLoading) {
    return (
      <motion.div
        initial={{ opacity: 0, x: 20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.6 }}
        className="flex flex-col items-center justify-center min-h-[600px] gap-8"
      >
        <Spinner size="lg" />
        <div className="text-center">
          <motion.p
            key={loadingMessageIndex}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            transition={{ duration: 0.3 }}
            className="text-zinc-300 font-medium"
          >
            {loadingMessages[loadingMessageIndex]}
          </motion.p>
        </div>

        {/* Skeleton loaders */}
        <div className="w-full space-y-4">
          {[1, 2, 3].map(i => (
            <div key={i} className="bg-zinc-800 rounded-xl h-24 animate-pulse" />
          ))}
        </div>
      </motion.div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      transition={{ duration: 0.6 }}
      className="space-y-6"
    >
      <Card>
        <TabBar tabs={tabs} activeTab={activeTab} onChange={setActiveTab} />

        <div className="mt-6">
          <AnimatePresence mode="wait">
            {activeTab === 'itinerary' && (
              <motion.div
                key="itinerary"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.3 }}
              >
                <ItineraryTab
                  finalAnswer={result!.finalAnswer}
                  destination={result!.destination}
                  duration={result!.duration}
                  budgetLevel={result!.budgetLevel}
                  budgetCurrency={result!.budgetCurrency}
                />
              </motion.div>
            )}
            {activeTab === 'weather' && (
              <motion.div
                key="weather"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.3 }}
              >
                <WeatherTab destination={result!.destination} />
              </motion.div>
            )}
            {activeTab === 'currency' && (
              <motion.div
                key="currency"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.3 }}
              >
                <CurrencyTab
                  destination={result!.destination}
                  budgetCurrency={result!.budgetCurrency}
                  budgetAmount={result!.budgetAmount}
                />
              </motion.div>
            )}
            {activeTab === 'destination' && (
              <motion.div
                key="destination"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.3 }}
              >
                <DestinationTab destination={result!.destination} />
              </motion.div>
            )}
            {activeTab === 'trace' && (
              <motion.div
                key="trace"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.3 }}
              >
                <AgentTraceTab steps={result!.intermediateSteps} />
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </Card>

      {/* Action buttons */}
      <div className="flex gap-4">
        <Button
          variant="secondary"
          size="md"
          className="flex-1"
          onClick={downloadPlan}
        >
          <Download size={20} />
          Download Plan
        </Button>
        <Button
          variant="secondary"
          size="md"
          className="flex-1"
          onClick={onReset}
        >
          <RotateCcw size={20} />
          New Trip
        </Button>
      </div>
    </motion.div>
  );
};

